### PR TITLE
[DOXIASITETOOLS-340] Rearrange title order in Velocity context

### PR DESCRIPTION
**Pull request by michael-o**
This closes #157

### CODE REVIEW

**Comment by kwin** [comment]
This contradicts the description in https://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Title.

**Comment by michael-o** [comment]
> This contradicts the description in https://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Title.

Good catch, will update.

**Comment by michael-o** [comment]
> This contradicts the description in https://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Title.

As a side note, this page needs a complete rework for the new site model.

**Comment by michael-o** [comment]
> This contradicts the description in https://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Title.

Issue created: https://issues.apache.org/jira/browse/MSITE-1007

**Comment by michael-o** [comment]
@kwin Is the change itself acceptable?

**Comment by michael-o** [comment]
@kwin If you don't have any objections, I will merge this today and start the release. The doc update will haven in MSITE.

**Comment by jira-importer** [comment]
Resolve #288

**Pull request closed without merging**
