### PR TITLE
[DOXIASITETOOLS-252] Add Apache Analytics attributes in DecorationModel

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
I consider this to be wrong here. This should be part of <custom /> element. This isn't really of general interest.

This does not require any changes with Doxia at all.

**Comment by olamy** [comment]
We already have google so we could at least have Apache related stuff here...

**Comment by michael-o** [comment]
True, and I consider this as a mistake. The custom element provides all you need. Have you evaluated it at all? The problem by putting this into Doxia Sitetools is you will ned to update the *entire* stack for this. Keeping it in `custom` only requires a skin change.

**Comment by olamy** [comment]
makes sense

**Pull request closed without merging**
